import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/Nav/Navbar";

const kanit = Kanit({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "thai"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="thai">
      <body className={kanit.className}>
        <main className="min-h-screen">
          <Provider>
            <Navbar />
            {children}
            <Toaster />
          </Provider>
        </main>
      </body>
    </html>
  );
}
